### ISSUE TITLE
Help Needed to Understand Error Message on 'grapher' and 'reconstruct'

### ISSUE THREAD

**Issue by YX-Xiang** [Tharos-ux/pancat#43]
Thank you for developing Pancat! It has been really helpful for my project.

However, I am encountering an error that I do not fully understand. The gfa files I use are generated by pggb or minigraph-cactus and there are no formatting issues. Here is the error message I am receiving:

<img width="599" alt="image" src="https://github.com/Tharos-ux/pancat/assets/44522917/4175337f-152b-4e42-bac9-5178bad7eabb">

I am sure this gfa file is not more than 10k nodes. So I guessed if I need to provide the boundaies parameter, but unfortunately it still reports an error:

<img width="596" alt="image" src="https://github.com/Tharos-ux/pancat/assets/44522917/8f13bde0-51ed-4fed-b679-ca434c368c70">

I can't pinpoint why this would cause the above error for 'pancat graper', and I'm having the same problem when running 'reconstruct':

<img width="604" alt="image" src="https://github.com/Tharos-ux/pancat/assets/44522917/b82e4f8c-1bdd-44ed-9cdf-7742ac3be9f9">

I wasn't sure if the 'out' parameter should be a folder path or a file path, so I tried each, but I still have the problem.

Could you please help me understand why these errors are occurring and how I might resolve them?

Thank you in advance for your assistance!

**Comment by Tharos-ux** [comment]
Hello, and thanks for your inquiry.
As for your first error, it was a typo I made, and I just made a commit to fix it.
For the second with `reconstruct`, it was kinda the same; was messing with names, and forget to replace a reference.
For reconstruct, it should work just fine now - pull the latest commit, install, and let me know if you have any issues!
I will work on an underlying issue with lib changes that occur on `grapher`, and will let you know once it's fixed aswell.

**Comment by Tharos-ux** [comment]
`grapher` seems to work perfectly fine now, with commit https://github.com/Tharos-ux/gfagraphs/commit/76c5fe2597b1fd34014a1d0b1ea35bb72196c860. Please do upgrade dependency `gfagraphs` with `pip install gfagraphs --upgrade`, and let me know if you still have issues.
Have a nice day :)

**Comment by Tharos-ux** [comment]
`compress` and all functions that need to write to a modified gfa seems to work now, with commit https://github.com/Tharos-ux/gfagraphs/commit/d57dbd7ddb3d02e37a94f152883ce4cf0f5b6478.
Again, please do upgrade dependency gfagraphs with pip install gfagraphs --upgrade, and let me know if you still have issues.
Please note tho that `compress` is WIP and is not 100% tested for production use (see pancat --help). I shall add it to the manpage. It was tested on human and yeast graphs, such as the ones from the HPRC, but no systematic testing was performed.
Have a nice day !
